version: "3"

services:
  db:
    container_name: db_container
    image: postgres:14
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    container_name: backend_container
    environment:
      TZ: "Europe/Moscow"
    image: backend:0.1.0
    volumes:
      - ./backend/migrations/versions:/backend/migrations/versions
    env_file:
      - ./backend/.env
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
