version: "3"

services:
  db:
    container_name: db_container
    image: postgres:14
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  mongo:
#    container_name: mongo_container
#    build:
#      context: ./mongo
#      dockerfile: mongo.dockerfile
#    volumes:
#      - ./mongo/data:/data/db
#    ports:
#      - "27017:27017"

  backend:
    container_name: backend_container
    environment:
      TZ: "Europe/Moscow"
    image: backend:0.1.0
    volumes:
      - ./backend/alembic/versions:/app/alembic/versions
    env_file:
      - ./backend/.env
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    volumes:
      - ./static/:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
