"""updated_user_and_vacancy_tables

Revision ID: 6ef00f3accda
Revises: 5a38c105ed2b
Create Date: 2024-10-05 13:17:44.323078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef00f3accda'
down_revision: Union[str, None] = '5a38c105ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen_time_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('screen_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vacancy', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy', 'user', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'recruiter_id')
    op.drop_table('screen_time_metrics')
    # ### end Alembic commands ###
