"""some updates

Revision ID: 57a6149ba5e5
Revises: 8a064488aeab
Create Date: 2024-10-06 01:30:52.761064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a6149ba5e5'
down_revision: Union[str, None] = '8a064488aeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_candidate_to_vacancy_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'hire_quality_metrics', 'user', ['recruiter_name'], ['name'])
    op.create_foreign_key(None, 'screen_time_metrics', 'user', ['recruiter_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screen_time_metrics', type_='foreignkey')
    op.drop_constraint(None, 'hire_quality_metrics', type_='foreignkey')
    op.drop_table('average_candidate_to_vacancy_metrics')
    # ### end Alembic commands ###
