"""add new table

Revision ID: 2187dd6259d0
Revises: 353565055145
Create Date: 2024-10-06 14:10:30.987777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2187dd6259d0'
down_revision: Union[str, None] = '353565055145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_cost_comparison_metrics',
    sa.Column('is_referral', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_cost_comparison_metrics')
    # ### end Alembic commands ###
