"""smth

Revision ID: 6c378094dcbe
Revises: 6ef00f3accda
Create Date: 2024-10-05 13:28:43.284742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c378094dcbe'
down_revision: Union[str, None] = '6ef00f3accda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hire_quality_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('screen_time_metrics', sa.Column('recruiter_name', sa.String(), nullable=True))
    op.add_column('screen_time_metrics', sa.Column('value', sa.Float(), nullable=True))
    op.drop_constraint('screen_time_metrics_recruiter_id_fkey', 'screen_time_metrics', type_='foreignkey')
    op.drop_column('screen_time_metrics', 'recruiter_id')
    op.drop_column('screen_time_metrics', 'screen_time')
    op.add_column('user', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salary')
    op.add_column('screen_time_metrics', sa.Column('screen_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screen_time_metrics', sa.Column('recruiter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('screen_time_metrics_recruiter_id_fkey', 'screen_time_metrics', 'user', ['recruiter_id'], ['id'])
    op.drop_column('screen_time_metrics', 'value')
    op.drop_column('screen_time_metrics', 'recruiter_name')
    op.drop_table('hire_quality_metrics')
    # ### end Alembic commands ###
