"""another_fix

Revision ID: ba07a7d1a019
Revises: 3f0837e02fdf
Create Date: 2024-10-06 10:56:39.326783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba07a7d1a019'
down_revision: Union[str, None] = '3f0837e02fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_candidate_to_vacancy_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hire_time_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_cost_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('vacancy_cost_metrics')
    op.drop_table('hire_time_metrics')
    op.drop_table('average_candidate_to_vacancy_metrics')
    # ### end Alembic commands ###
