"""added new metrics

Revision ID: 3e8408ffa53c
Revises: 2187dd6259d0
Create Date: 2024-10-06 17:42:05.974300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8408ffa53c'
down_revision: Union[str, None] = '2187dd6259d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_satisfaction_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_satisfaction_metrics')
    # ### end Alembic commands ###
