"""changed field to foreign key

Revision ID: 5a38c105ed2b
Revises: a0fa6302b66b
Create Date: 2024-10-05 10:11:35.652622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a38c105ed2b'
down_revision: Union[str, None] = 'a0fa6302b66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidate', 'vacancy', ['vacancy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    # ### end Alembic commands ###
